version: '3'

services: 
    app:
        image: app_img
        container_name: app_cont
        build: 
            context: ./docker/dotnet/
        ports: 
            - 5000:80
        command: ["dotnet", "watch", "run"]
        tty: true