version: '3'

services: 
  app:
    image: app_img
    container_name: app_cont
    build: 
      context: ./docker/dotnet/
      args:
        - HTTP_PROXY=192.168.100.230:8080
        - HTTPS_PROXY=192.168.100.230:8080
    ports: 
      - 5000:80
    volumes: 
      - ./shared:/shared
    tty: true
  db:
    image: postgres:11
    container_name: db_cont
    ports: 
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./docker/postgres/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/postgres/initializesql:/initializesql
    tty: true